#pragma once

// Where each replaced function lives in the game being built.
//
// The runtime replaces ~580 guest functions with native code, and every
// registration names the address that function has in Mario Kart Wii. Almost all
// of them are Nintendo SDK routines that every Wii game carries, at its own
// addresses - so the addresses belong to the game, not to the runtime.
//
// A game supplies a table of them (generated by example-wii-nx's resolve-symbols
// from the game's own code) and every registration looks itself up here by name,
// falling back to the address written at the call site. With no table, which is
// the case for Mario Kart Wii itself, nothing changes.
//
// A function the table does not mention is one that game does not have, or one
// we could not find in it: Resolve reports 0 and the registration is dropped, so
// the translated original runs instead of a replacement pointed at the wrong
// address.

#include <cstdint>
#include <cstring>

namespace NativeBindings {

struct Binding {
    const char* name;      // the C++ symbol the runtime registers
    std::uint32_t address; // where that function is in this game
};

// The game's table, sorted by name. The default is empty; a game that needs one
// links a generated file defining these instead (see make-bindings).
extern const Binding* Table() noexcept;
extern std::size_t TableSize() noexcept;

// True when a game supplied a table at all.
inline bool Present() noexcept { return TableSize() != 0; }

// The address to register `name` at. `fallback` is what the call site says,
// which is right for the game the runtime was written against.
inline std::uint32_t Resolve(const char* name, std::uint32_t fallback) noexcept {
    const std::size_t count = TableSize();
    if (count == 0) {
        return fallback;
    }
    const Binding* table = Table();
    std::size_t low = 0;
    std::size_t high = count;
    while (low < high) {
        const std::size_t middle = low + (high - low) / 2;
        const int order = std::strcmp(table[middle].name, name);
        if (order == 0) {
            return table[middle].address;
        }
        if (order < 0) {
            low = middle + 1;
        } else {
            high = middle;
        }
    }
    // Not in this game, or not found in it: no replacement, so the game's own
    // code runs. Better a slow original than a fast wrong one.
    return 0;
}

}  // namespace NativeBindings
